# Base configuration
permalink: /news/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# #Prose.io editing info
# repo_name: doi-data-hub
# branch: gh-pages
# #GitHub organization name *or* username
# gh_org: USInterior
# prose_url: http://prose.io
# site_url: http://usinterior.github.io/doi-data-hub
# media: assets/img


# Your Programs's Name
name: Department of the Interior Data Hub
subtitle: A hub for data at the Department of the Interior

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/doi-data-hub'

# Author/Organization info to be displayed in the templates
author:
  name: U.S. Department of the Interior
  url: http://localhost:4000

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------

navigation:
- text: Home
  url: index.html
  internal: true
- text: Featured Data
  url: pages/featured_data.html
  internal: true
- text: Full Data Catalog
  url: pages/data_catalog.html
  internal: true
- text: Feedback
  url: pages/feedback.html
  internal: true
- text: News
  url: pages/news.html
  internal: true
- text: Developers
  url: pages/developers.html
  internal: true
- text: Open Data at DOI
  url: pages/open_data.html
  internal: true
