#
# This is the main data file for your project.  Change the values
# below accordingly.
# See http://yaml.org for details about YAML
#
org_name:  FBOpen
org_abbrev:
address:
 street: 1800 F St NW
 suite:
 city: Washington
 state: D.C.
 zip: 20240
point_of_contact: Michelle Hertzfeld
# A valid HREF--email, form, etc.
poc_link: mailto:michelle.hertzfeld@gsa.gov
sponsoring_office: 18F
logo_url:
logo_alt:
home_url: index.html
